lint:
  actions_ci: false
  files_unchanged:
    - .gitignore
    - assets/nf-core-riboseq_logo_light.png
    - docs/images/nf-core-riboseq_logo_dark.png
    - docs/images/nf-core-riboseq_logo_light.png
  nextflow_config:
    - config_defaults:
        - params.ribo_database_manifest
nf_core_version: 3.1.1
repository_type: pipeline
template:
  author: Jonathan Manning
  description: Analysis of ribosome profiling, or Ribo-seq (also named ribosome footprinting)
  force: false
  is_nfcore: true
  name: riboseq
  org: nf-core
  outdir: .
  version: 1.1.0dev
